name: Genera EPG

on:
  schedule:
    - cron: "0 4 * * *"   # ogni giorno alle 04:00 UTC
  workflow_dispatch:      # avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui script
        run: python genera_epg.py

      - name: Commit e push file EPG
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add 04.epg
          git commit -m "Aggiornamento automatico EPG" || echo "Nessuna modifica"
          git push
