name: Update EPG 04

on:
  schedule:
    # Esecuzione alle 05:00 UTC (06:00 o 07:00 in Italia)
    - cron: '0 5 * * *'
  workflow_dispatch: # Permette l'avvio manuale dalla scheda "Actions"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Versione aggiornata

      - name: Set up Python
        uses: actions/setup-python@v5 # Versione aggiornata
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG Update script
        run: python update_epg.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add 04.xml
          git commit -m "Update EPG 04.xml - $(date)" || echo "No changes to commit"
          git push
